name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build & Push
      run: |
        cd ./GoWork
        echo "${{ secrets.DOCKERPW }}" | docker login -u "spbravo" --password-stdin
        docker image build -t spbravo/gitops:go1.0 .
        docker push spbravo/gitops:go1.0
      
